# Generated by Django 3.1.1 on 2021-02-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='category_icon',
            field=models.ImageField(blank=True, default='category_icons/default.png', upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, default='category/default.jpg', upload_to='category/'),
        ),
    ]
