# Generated by Django 3.1.1 on 2021-02-19 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_analytics', '0001_initial'),
        ('core', '0011_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_auto_20210219_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='impression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_analytics.impression'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='primary_image',
            field=models.ImageField(blank=True, default='services/primary-images/default.jpg', upload_to='services/primary-images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pricingplan'),
        ),
    ]
