# Generated by Django 3.1.1 on 2021-02-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_photo'),
        ('services', '0003_auto_20210219_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.ManyToManyField(blank=True, to='core.FeatureItem'),
        ),
    ]
