# Generated by Django 3.1.1 on 2021-02-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_impression'),
        ('service_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='services.service'),
            preserve_default=False,
        ),
    ]
