# Generated by Django 3.1.1 on 2020-12-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201228_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureitem',
            options={'ordering': ('feature_key',)},
        ),
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
