# Generated by Django 3.1.1 on 2020-12-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201229_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='category_icon',
            field=models.ImageField(default='category_icons/default.png', upload_to='category_icons/'),
        ),
    ]
