# Generated by Django 3.1.1 on 2020-12-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicecategory_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(default='service_icons/default.png', upload_to='service_icons/'),
        ),
    ]
