# Generated by Django 3.1.1 on 2020-12-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(default='category/default.jpg', upload_to='category/'),
        ),
    ]
