# Generated by Django 3.1.1 on 2021-02-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201231_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pricing',
        ),
    ]
