# Generated by Django 3.1.1 on 2021-02-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
